### ISSUE TITLE
Delivery planning for Class Induction & Git

### ISSUE THREAD

**Issue by caromelendezl** [CodeYourFuture/glasgow-class-6#16]
[Agenda
](https://docs.google.com/spreadsheets/d/1fPp2Gk3RARrTpW0tH0y1PLWhoCN2EkyXGT2ZRchfP58/edit#gid=1132051867)

Alastair Cooper [22 Sep at 18:36]
Need to check availability and desire to participate given new dates.

**Comment by emcglackenr1** [comment]
Trainee number appears to be 30

**Comment by sztupy** [comment]
Alastair/Zsolt Raven/Michael Simm to teach + prepare plan for the day and share schedule in week before with Trainees and TAs

**Comment by SallyMcGrath** [comment]
This class has happened
