### ISSUE TITLE
Plan for HTML/CSS Module

### ISSUE THREAD

**Issue by sztupy** [CodeYourFuture/glasgow-class-6#53]
Plan for HTML/CSS module

~~Module coordinator? Maybe Coung - or anyone else who would like to step up~~

Check in with PD volunteers, are they good with interlacing the PD with the 4 weeks of the module?

@gregdyke had mentioned Ivan, Tara and Andy as well.

**Comment by sztupy** [comment]
Coung will likely not be available for this anymore, we might need to find another volunteer

**Comment by beardedslav** [comment]
I can do it!
