### ISSUE TITLE
Check new volunteers' GitHub access rights

### ISSUE THREAD

**Issue by sztupy** [CodeYourFuture/glasgow-class-6#54]
* Make sure all volunteers can edit, assign and be assignable on the Kanban board
* Double check the Google Form

**Comment by emcglackenr1** [comment]
Will contact CYF staff who are admins of Github to ensure this works

**Comment by SallyMcGrath** [comment]
Volunteers just need to [Join their Github Team](https://docs.google.com/forms/d/e/1FAIpQLSdemxZcis60fP7MfjKRP22XvhLwhRa5qVE6ujp9MDN2sqjWDw/viewform)

Once members of our Github org, you can make your own sub teams inside [Scotland Mentors](https://github.com/orgs/CodeYourFuture/teams/scotland-mentors/members) to organise anything in any way that makes sense for you.

Projects can belong to this team, and you can have discussion boards as well.
