### ISSUE TITLE
Organise Laptops for New Cohort

### ISSUE THREAD

**Issue by caromelendezl** [CodeYourFuture/glasgow-class-6#58]
- [x] Boot two remaining wiped new laptops (Lenovo) in KPC Storage Cupboard with Ubuntu
 - [x] Chase up everyone who is not a current student/job-hunting alumni for their laptop

**Comment by emcglackenr1** [comment]
Tandy Nicole [6 Nov at 03:23]
Yes they were @alastair876 and what information are you looking for?

Alastair Cooper [5 Nov at 23:04]
@tandynicole My understanding was that you collected some laptops for CodeYourFuture - I thought those were donations but maybe I misunderstood.

Tandy Nicole [5 Nov at 22:28]
What details are you looking for @alastair876? the laptops I have are not related to this ticket so I am confused

Alastair Cooper [3 Nov at 18:46]
@tandynicole - do you have the details of the laptops you received?

Gianluca [6 Oct at 14:39]
I might have time on Sunday to boot the laptops and check that first item off the list. I'll let you know! I think checkbox two, three and four should be done by next PROM - there's probably no mad rush on them.

Tandy Nicole [6 Oct at 13:46]
Could we please check the list or create a new ticket @gianlucapalombo @GianLucaS p and @irinapreda1

Gianluca Palombo [5 Aug at 14:55]
All students currently have a laptop







AM(AightA) to drop off laptop that's no longer needed 

Details:
_'It was between Alastair and prev mentor who relocated outside UK.'_

**Comment by emcglackenr1** [comment]
See comment notification from G on slack 20/12/2022

**Comment by caromelendezl** [comment]
@emcglackenr1 this was created in the old kanban. almost sure I've seen another ticket with Laptop inventory.
Should we close this and move it to Done?

**Comment by emcglackenr1** [comment]
Removed aspects about recycling and sending laptops back, added to new card

**Comment by emcglackenr1** [comment]
.
