### ISSUE TITLE
Questions about Scotland groups/teams on Github

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/glasgow-class-6#59]
AM asked for clarification on the teams in Scotland on GitHub

![Image](https://user-images.githubusercontent.com/64873698/208701112-640abe79-d8c9-42cc-823e-2bcfe5394cec.png)

**Comment by emcglackenr1** [comment]
He added that Glasgow-class-3 isn’t there. It would be good to clarify why it is set up this way

**Comment by emcglackenr1** [comment]
@SallyMcGrath is this something you can set up? Or is it not necessary?

**Comment by gregdyke** [comment]
IMO it's not worth setting up. It's only for repo access (dunno how we did class 3). If the person needs repo access, they should be a mentor

**Comment by SallyMcGrath** [comment]
I feel like I answered this exact question last week. Am I going mad or have two tickets about the same thing been created? (You can add tickets to multiple boards if this is useful.)

**Comment by SallyMcGrath** [comment]
Found it. My response copied below:

They just never made one so it doesn't exist. There's no obvious point making one now as the github team is just for operational reasons to manage a running class, trackers, and coursework repo access.

Here's the Tech Ed Tools lesson on this

https://codeyourfuture.openclass.ai/resource/lesson-62a6f8ec20ddf1eb0bd8fcf2?code=7Xa23K3_ybMRpQ
