### ISSUE TITLE
Logistics Class 14/01/2023

### ISSUE THREAD

**Issue by caromelendezl** [CodeYourFuture/glasgow-class-6#63]
Discuss:

- [x] Set up hardware - Get input
- [x] Food - see below  - Get input
- [x] [Agenda](https://docs.google.com/spreadsheets/d/1am4Zfqb-wQrnP0gNEzm8UWTJjHGchyfeIJp1BnPCuoU/edit#gid=38213273)

**Comment by emcglackenr1** [comment]
@caromelendezl 
- [ ] Pret a Manger - donated in the past. They label food in terms of if it's veggie 
- [ ] Too Good to Go - ?? Could find information about companies that might be willing to help

**Comment by emcglackenr1** [comment]
Hardware - 
Laptop configeration:

- [x] Ones Gianluca set up had basic configuration - are they suitable? so he might only have install ubuntu and nothing else 
- [x] Some in cupboard might have basic configuration - check

How do we check?
- Do they have ubuntu?
- If computer has unique name written on side of box it is likely configured


Do trainees all have laptops?
Have laptops been wiped for personal data? (e.g. ones handed in by volunteer T)

We don't support windows anymore - important for React onwards.
