### ISSUE TITLE
Module coordinator

### ISSUE THREAD

**Issue by caromelendezl** [CodeYourFuture/glasgow-class-6#64]
- [ ] @emcglackenr1 to follow steps below so volunteers can set it up amongst themselves

Beyond having a module coordinator (who ensures that the overall objectives of any given module are met during that module, even if some shuffling/changing of material happens), there is some continuity that is hard for volunteers to track over the whole course (because of not being involved every week/every module). There is also some looping of improvements back into the syllabus that tends to not happen

- what is the material that has not been covered during a given module (typically some "extra" material that is not core to the module, but sometimes certain concepts, such as http requests have not been seen in any depth)
- what assumptions can the next module coordinator make about the syllabus so far (e.g. going into JS2, have students all systematically run tests from the command line? Or is that something that needs deliberately re-visiting?)
- based on the retro of the last module, what changes should we bring into the next module (these tend to be cohort-specific)
- based on the retro of the last module, what feedback should be provided to the syllabus module team?
- what resources were created during the module (slides, visual aides, videos, additional exercises, demos) that would be good to put into the syllabus so that other cities/future cohorts have access

**Comment by SallyMcGrath** [comment]
None of this should be done by you, btw.

**Facilitate** tech Ed to do this by:

- [ ] Putting a **signup sheet** somewhere for people to sign up to organise modules and personally invite likely candidates
- [ ] List out this stuff as things for them to consider as a checklist (example below)
- [ ] Keep it simple!

## The Module Coordinator will

1. read [the syllabus](https://syllabus.codeyourfuture.io/html-css/) for their module
2. hold a [30 minute planning call](https://teachertraining.codeyourfuture.io/roles/lead-teacher/teaching-a-session-at-cyf) once a week to confirm and assign sessions on the agenda
3. [check and schedule](https://classroom.google.com/c/NTgyOTY4MTI1Nzgy) the coursework for the module on google classroom
4. attend or organise a 1 hour code review session once a week (or just join the [global one](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=MnF0ZnJzanY2N2tib2JtbGIycTFyYzMwZThfMjAyMzAxMjVUMTIwMDAwWiBjb2RleW91cmZ1dHVyZS5pb190bTQwM3Q1OWY1YnNyOWhybXRsZXI3ZGJpOEBn&tmsrc=codeyourfuture.io_tm403t59f5bsr9hrmtler7dbi8%40group.calendar.google.com&scp=ALL))
5. **hand over to the next module coordinator**

Then you can leave all the operational details to Tech Ed

**Comment by emcglackenr1** [comment]
Thanks Sally, I've assigned this to me so I can do the aspects we need to to facilitate volunteers taking this on, and put a note in the description
