### ISSUE TITLE
Buddy Groups

### ISSUE THREAD

**Issue by caromelendezl** [CodeYourFuture/glasgow-class-6#67]
Card connected to #68 - PD volunteers
Card connected to #91 

PD roles
https://docs.codeyourfuture.io/volunteers/teams-1/personal-development/roles
Buddy Guide PD[ https://docs.codeyourfuture.io/volunteers/teams-1/personal-development/mentor-guide](https://docs.codeyourfuture.io/volunteers/teams-1/personal-development/mentor-guide)
Education buddy
https://docs.codeyourfuture.io/volunteers/teams-1/tech-education/education-roles/education-buddy

- [x] Dara and Caro to ask Gianluca’s thoughts as he organised buddies in Scotland before ([done](https://codeyourfuture.slack.com/archives/C04KMQ0DUM6/p1675098109379759))
- [x] Dara to discuss with Elizabeth about her recommendations regarding english language levels [(done)](https://codeyourfuture.slack.com/archives/C029341FPH6/p1675097899123679?thread_ts=1674664867.948229&cid=C029341FPH6)
- [x] Groups to be organised by Caro and Dara
- [x] Volunteer buddies to be informed that: If there are issues with the buddy groups, volunteer buddies can highlight this and help to support finding a solution

**Comment by gregdyke** [comment]
I think the "buddy group" function is properly documented somewhere (number of trainees per group, how often they ideally meet, how much work is expected of the Volunteer assigned to that group).

Of the top of my head, we should form these groups as soon as we know the list of trainees in the cohort. Make it groups of 3-5 and assign them a Volunteer as the volunteers come forward (/get recruited).

Although the Volunteer is useful to make sure stuff is happening and update the team with info about their "trainees", having each trainee be part of an official group who they meet with at least once per week + give each other feedback should happen ASAP

**Comment by caromelendezl** [comment]
@gregdyke 
in the process of "recruiting" volunteers for these roles. I'll mentioned this issue againon Slack and also in the region's newsletter this week

**Comment by caromelendezl** [comment]
Dar-Emma and Caro to meet on 25th Jan to discuss

**Comment by MarianaVazquezCYF** [comment]
Hey Caro, how many more edu buddies do you need?

**Comment by msimmdev** [comment]
Hi @caromelendezl, just wanted to highlight that we discussed this in our volunteer retro this week as trainees had some confusion on coursework and deadlines. We thought in the future we could mitigate this with buddies.

I took an action to raise it with you, but I see it's well in hand

**Comment by emcglackenr1** [comment]
In progress
