### ISSUE TITLE
Support trainee H with Chromebook

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/glasgow-class-6#73]
Resolved :
We do not have the resources to support Chrome Book issues, so easier to give him a laptop
Gla-6 trainee Hussein said that he was unable to set up properly using his Chromebook.

**Comment by emcglackenr1** [comment]
- [ ] Give him a laptop

**Comment by emcglackenr1** [comment]
He couldn't find much support online for it.

He said that if this cannot be set up he might need to request a laptop from us. 


- [ ] Look into installing Github desktop on Chromebook.

- [ ] Also push and pull suited for Ubuntu.

**Comment by alastair87** [comment]
This is the tooling for running Linux software on a Chromebook:

https://chromeos.dev/en/linux

The actual OS it runs is already a version of Linux but this provides a Debian container that can run general Linux applications, not just those for ChromeOS. In theory it should run everything he needs, but our policy is only to support Ubuntu and Mac.
