### ISSUE TITLE
Set up GitHub tracker for Glasgow-6

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/glasgow-class-6#77]
- Claire has invited trainees who have filled out the form
- But many haven't done that yet

**Comment by emcglackenr1** [comment]
[Notes in agenda/drop in](https://docs.google.com/spreadsheets/d/1fPp2Gk3RARrTpW0tH0y1PLWhoCN2EkyXGT2ZRchfP58/edit#gid=93637665)

**Comment by emcglackenr1** [comment]
Blocked because waiting for trainees to confirm/fill out form

**Comment by SallyMcGrath** [comment]
Here's a helpful video that explains this to trainees.

https://www.youtube.com/watch?v=9Tpk03qzndc&list=PLozA7cloMbPiOvZnMvPGwdQCAeEAroGfR&index=2
