### ISSUE TITLE
Organise JS1 Module

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/glasgow-class-6#82]
Module co-ordinator: @gregdyke has offered to do this

- [x] Set meeting about organising JS1 
- [x] @caromelendezl  to discuss with Greg potential volunteers who are currently inactive or not as involved who he could encourage to support him with this module
- [x] any on @CodeYourFuture/scotland-mentors would like to participate?

**Comment by caromelendezl** [comment]
@gregdyke when do you have some time this week to chat about volunteers? Karin has mentioned she would like to participate  as Lead Teacher but she can do it for the 1st 3 sessions/weekends only

**Comment by gregdyke** [comment]
I'll be there on Friday, but could do earlier. I'm not entirely sure what a "Lead Teacher" does in the flipped classroom model, but there is definitely some working through codewars + facilitating Q&A that needs doing

**Comment by Cee-tech21** [comment]
Is there an existing JS1 module?

**Comment by Cee-tech21** [comment]
DOM manipulation and API consumption could be used as broad tasks with which to guide a new JS1 module.
