### ISSUE TITLE
Get Instructions for KPC Sound System

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/glasgow-class-6#85]
Michael said that staff at KPC had offered to send instructions for the sound system. 
Would be helpful for future sound issues.

**Comment by emcglackenr1** [comment]
Dara emailed to get these instructions since they weren't recieved yet. Awaiting reply

**Comment by caromelendezl** [comment]
This has been received. @emcglackenr1, if you could please include this video link in the [Saturday class checklist draft doc](https://docs.google.com/document/d/1U7wK1MIrXfXdmYNTmc7MXfth0PLu26anNlmcbaARu4E/edit#heading=h.bitr91jvx0eu) and then close this card ;)
